### ISSUE TITLE
losoto/h5impcal crash [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by tikk3r** [revoltek/losoto#50]
As of late I am experiencing a pretty much guaranteed crash in some data reduction runs at the `h5impcal` step. It crashes with the error `[Errno 11] Resource temporarily unavailable` (see also https://github.com/lofar-astron/prefactor/issues/173 for more details). I have tried investigating a little bit with @oonkjbr, but it wasn't easily pinpointable to either LoSoTo, the pipeline or the genericpipeline framework. @lmorabit started experiencing this issue now as well with the long baseline pipeline.

Could this have something to do with LoSoTo or the combination LoSoTo + Genercipipeline?

It's not guaranteed to happen, but if it happens it is guaranteed crash the pipeline at this step. The resulting H5Parm is also not correct. We have seen this error happening now on either the Leiden cluster or on a GRID infrastructure, with both prefactor and the long baseline pipeline.

When running this step as a separate command, it seems to work fine. I do not know as of now if it is related to only losoto or the genericpipeline framework, but I do think this issue needs more attention in general, hence I'm raising it here as well.

Frits

**Comment by revoltek** [comment]
To me this:
self._addoutput(self.STDERR, self.process.stderr.read(4096))
IOError: [Errno 11] Resource temporarily unavailable
looks like a prefactor problem more than a losoto problem. I can definitely debug it if you can provide me an h5parm and a losoto parset that crashes.

**Comment by lmorabit** [comment]
It does indeed look like a generic pipeline issue.  I fixed this in the long baseline pipeline by changing the step that runs losotoImporter.py from a pythonplugin to a recipe, and now it works.  @tikk3r says they've been having the same trouble with prefactor, so I'll suggest the solution to them as well.

**Comment by mooneyse** [comment]
I think @tammojan has provided a fix for this now in NDPPP so it can probably be closed.

**Comment by tikk3r** [comment]
The issue is still present in KERN though. I tried to run prefactor 3.0 in a singularity container with the software installed from KERN-4 and it throws this error again. The software in there is built against HDF5 1.10.0. It could be a combination of DPPP maybe not opening them as read-only yet and HDF5 1.10 being strict with parallel access when a write lock is held.
It could technically happen with parallel losoto steps as well, but I haven't encountered this since anymore so at least on the losoto side it seems ok, if it ever was here in the first place.

**Comment by mooneyse** [comment]
Yeah I experience it still with the parallel Losoto steps and with KERN software, but I guess the problem isn't caused by Losoto ultimately.

**Comment by tikk3r** [comment]
> Yeah I experience it still with the parallel Losoto steps and with KERN software, but I guess the problem isn't caused by Losoto ultimately.

It might be (not saying it is). If one thread/process has a write lock on an H5 parm nothing else can access it. Not even as read-only.

**Comment by revoltek** [comment]
Since this was an old issue most likely related with pipeline, I close the issue
